core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("mainapps.accounts.urls",namespace='account')),
    path('stock/', include("mainapps.stock.urls",namespace='stock')),
    path('inventory/', include("mainapps.inventory.urls",namespace='inventory')),
    path('company/', include("mainapps.company.urls",namespace='company')),
    path('', include("mainapps.common.urls",namespace='common')),
    path('management/', include("mainapps.management.urls",namespace='management')),
    # path('permission/', include("mainapps.permit.urls",namespace='permission')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

mainapps/accounts/urls.py
from django.urls import path,include
from .views import *
app_name='accounts'
urlpatterns=[
    
    path('',register_owner,name = 'signup'),
    path('signout/',signout, name='logout'),
    path('signin/',login_owner, name='signin'),
    path('register/',RegisterPage.as_view(), name='register'),
    # path('signin/',signin, name='signin'),
    path('welcome/',LandingPage.as_view(), name='land'),
    path('verification/',twofa, name='verification'),
    path('send_code',send_code,name='send_code'),
]

mainapps/common/urls.py
from django.urls import path
from .views import *
app_name='common'
urlpatterns = [
    path('',HomEPage.as_view(),name='home'),
    path('add/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxTabGenericCreateView.as_view(), name='add_item'),
    
    
    ###################################################################################
    # ajax
    path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('add-address/', add_address, name='add_address'),
    path('get-regions/', get_regions, name='get_regions'),
    path('get-subregions/', get_subregions, name='get_subregions'),
    path('get-cities/', get_cities, name='get_cities'),
]

mainapps/management/urls.py
from django.urls import path
from .views import   *
app_name='management'


urlpatterns = [
    path('company-profile/', CompanyProfileCreateView.as_view(), name='company_profile'),
    path('login/', login_staff, name='login'),
    path('<str:company_id>/add-staff/', StaffUserCreateView.as_view(), name='add_staff_user'),
]

templates/dashboard/wrapper/base.html
{% load static %}
{% load bootstrap5 %}
{% load model_tags %}

{% block html %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
{% block head %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block more_meta_tags %}
    {% endblock %}
    <title>{% block page_title %}{% endblock page_title %}</title>
    <link href="{% static 'assets/dashboard/css/main.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
      href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&family=Poppins:wght@400;500;700&display=swap"
      rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    {% bootstrap_css %}
    {% block extra_style %}
    {% endblock extra_style %}
</head>
{% endblock head %}
{% block body %}
<body>
  {% bootstrap_messages %}
  {% include 'dashboard/wrapper/header.html' %}
  <main>
    <div class="e-container">
      
        <div class="e-offset-12 e-offset-md-3 e-offset-lg-2">
          {% block content %}
  
          {% endblock content %}
        </div>

        {% block in_page_scripts %}
        {% endblock in_page_scripts %}
      </div>
  </main>
  
  

    {% block script %}
    <script src="{% static 'assets/js/jQuery.js' %}"></script>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>

    <script src="{% static 'assets/dashboard/js/main.js' %}"></script>
    {% bootstrap_javascript %}
    {% block extra_script %}
    {% endblock extra_script %}
    {% endblock script %}
</body>
{% endblock body %}
</html>
{% endblock html %}

templates/dashboard/wrapper/footer.html
<footer class="bg-gray-800 text-white py-4 mt-20">
    <div class="container mx-auto text-center">
        <p>&copy; 2024 Pharm Praise. All rights reserved.</p>
    </div>
</footer>

templates/dashboard/wrapper/header.html
{% load static %}
<header class="e-header e-header-fixed e-d-flex e-justify-between e-align-center">
    <div class="e-container">
        <div class="e-offset-12 e-offset-md-3 e-offset-lg-2">
            <nav class="e-header__nav e-d-flex e-justify-between e-align-center">
                <div class="e-header__left e-d-flex e-align-center e-mg-r-10 e-mg-0-md">
                    <div class="e-header__mobile e-mg-r-10 e-d-none-md">
                        <button type="button" class="e-header__mobile--trigger e-icon-btn" data-menu-target="main-menu">
                            <i class="ri-menu-2-line e-fs-16"></i>
                        </button>
                    </div>
                    <div class="e-header__form">
                        
                        <form class="e-form">
                            <div class="e-form__group">
                            <input type="text" class="e-form__input" placeholder="Search...">
                            <i class="ri-search-line e-form__icon"></i>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- left header part ends -->
                  {% include 'dashboard/wrapper/sidebar.html' %}
                {% if user.is_authenticated %}
                <div class="e-header__right e-d-flex e-align-center ">
                    
                    <div class="e-dropdown e-dropdown-abs-right e-d-in-flex e-mg-r-20">
                        <button type="button" class="e-btn e-btn-secondary e-btn-sq"data-dropdown-target="settings">
                            <i class="bi bi-gear"></i>         
                        </button>
                  {% include 'dashboard/wrapper/settings.html' %}
                  
                
                    <div class="e-dropdown e-dropdown-abs-right e-d-in-flex e-mg-l-10">
                        <button type="button" class="e-btn e-btn-secondary e-btn-sq"data-dropdown-target="notifications">
                            <i class="bi bi-bell"></i>
                            <div class="e-bdg e-bdg-danger">6</div>
                        </button>
                            {% include 'dashboard/wrapper/notifications.html' %}
                    </div>
                    
                    <div class="e-dropdown e-dropdown-abs-right e-d-in-flex e-mg-l-10">
                        <button type="button" class="e-avat e-avat-35"data-dropdown-target="profile">
                        <img src="{% static 'assets/dashboard/images/user-f-1.jpg' %}" alt="" class="e-avat__img">
                        </button>
                            {% include 'dashboard/wrapper/profile.html' %}
                    </div>
                </div>
            </nav>
            {% else%}
            <div class="e-d-flex">
                <a class="nav-link e-fs-14 e-fw-bld e-d-flex" href="{% url 'account:signin' %}"> Signin</a>

                <a class="nav-link e-fs-14 e-fw-bld e-d-flex" href="{% url 'account:signup' %}"> Register</a>
            </div>
                
            {% endif %}
        </div>
    </div>
</header>

templates/dashboard/wrapper/notifications.html
<div class="e-dropdown__menu" id="notifications">
    <div class="dropdown-header e-pd-20">
        <h4 class="e-fw-bld">Notifications</h4>
    </div>
    <ul class="dropdown-content">
        <li class="dropdown-list">
            <a href="#" class="dropdown-link e-d-block e-pd-x-20 e-pd-y-10">
                <span class="notice-time e-fs-12">4:56 pm</span>
                <span class="notice-content e-fs-14 e-fw-bld">
                    Nkiruro order just dropped! check it out
                </span>
            </a>
        </li>
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-block e-pd-x-20 e-pd-y-10">
                <span class="notice-time e-fs-12">4:56 pm</span>
                <span class="notice-content e-fs-14 e-fw-bld">
                    Nkiruro order just dropped! check it out
                </span>
            </a>
        </li>
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-block e-pd-x-20 e-pd-y-10">
                <span class="notice-time e-fs-12">4:56 pm</span>
                <span class="notice-content e-fs-14 e-fw-bld">
                    Nkiruro order just dropped! check it out
                </span>
            </a>
        </li>
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-block e-pd-x-20 e-pd-y-10">
                <span class="notice-time e-fs-12">4:56 pm</span>
                <span class="notice-content e-fs-14 e-fw-bld">
                    Nkiruro order just dropped! check it out
                </span>
            </a>
        </li>
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-block e-pd-x-20 e-pd-y-10">
                <span class="notice-time e-fs-12">4:56 pm</span>
                <span class="notice-content e-fs-14 e-fw-bld">
                    Nkiruro order just dropped! check it out
                </span>
            </a>
        </li>
    </ul>
    <div class="dropdown-footer e-pd-20">
        <button type="button" class="e-btn e-btn-secondary e-btn-link">Mark all as read</button>
    </div>
</div>

templates/dashboard/wrapper/profile.html
{% load static %}
<div class="e-dropdown__menu" id="profile">
    <div class="dropdown-header e-pd-20">
        <div class="e-d-flex e-align-center">

            <div class="user-img e-mg-r-10">
                <div  class="e-avat e-avat-50">
                    <img src="{% static 'assets/dashboard/images/user-f-1.jpg' %}" alt="" class="e-avat__img">
                </div>
                
            </div>
            <div class="user-detail">
                <span class="e-fs-14 e-fw-bld e-d-block">Ubong Prosper</span>
                <span class="e-fs-12  ">Founder: Intera Inventory</span>
            </div>
        </div>
    </div>
    <ul class="dropdown-content">
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-flex e-pd-x-20 e-pd-y-10">
                <i class="bi bi-gear  e-fs-14 e-mg-10"></i>
                <span class=" e-fs-14 e-fw-bld">
                    Account Settings 
                </span>
            </a>
        </li>
    </li>
        


        
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-align-center e-d-flex e-pd-x-20 e-pd-y-10">
                <i class="ri-user-star-line e-fs-14 e-mg-10"></i>
                <span class=" e-fs-14 e-fw-bld">
                    Tasks
                </span>
            </a>
        </li>
        
        <li class="dropdown-list">
            <a href="#" class="e-dropdown-link e-d-flex e-pd-x-20 e-pd-y-10">
                <i class="ri-user-star-line e-fs-14 e-mg-10"></i>
                <span class=" e-fs-14 e-fw-bld">
                    Todo
                </span>
            </a>
        </li>
        
    </ul>
    <div class="dropdown-footer ">
        <a href="{% url 'account:logout' %}" class="e-dropdown-link e-d-flex e-pd-x-20 e-pd-y-10">
            <i class="ri-user-star-line e-fs-14 e-mg-10"></i>
            <span class=" e-fs-14 e-fw-bld">
                Logout
            </span>

        </a>
    </div>
</div>

templates/dashboard/wrapper/settings.html
{% load model_tags %}
<div class="e-dropdown__menu" id="settings">
    <div class="dropdown-header e-pd-20">
        <h4>Settings</h4>
        
    </div>

    <ul class="navbar-nav ms-auto">
        <li class="nav-item">

            <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'common:home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link e-fs-14 e-fw-bld dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Management Settings
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% settings user %}

                
            {% if user.company and user.is_main %}
            <li class="nav-item">
                <a class="dropdown-item e-fs-14 e-fw-bld dropdown-toggle" href="{% url 'management:add_staff_user' user.company.encrypted_id %}">Manage Staff </a>
            </li>
         {% elif user.is_main %}    
            <li class="nav-item">
                <a class="dropdown-item e-fs-14 e-fw-bld dropdown-toggle" href="{% url 'management:company_profile'  %}">Company Profile</a>
            </li>

        {% endif %} 
            </ul>
        
        {% endif %}
    </ul>
</div>

templates/dashboard/wrapper/sidebar.html
{% load static %}
{% load model_tags %}

<ul class="e-header__navitems e-header__sidebar-md-3 e-header__sidebar-lg-2 e-pd-y-20" id="main-menu">

    <li class="e-header__list">
      <a href="/" class="e-header__link--logo e-pd-20 e-d-flex e-align-center e-justify-center">
        <img src="{% static 'assets/dashboard/images/ease-logo.svg' %}" alt="Ease Dashboard logo">
      </a>
    </li>

    <li class="e-header__list e-dropdown">
      <a href="#"style="text-decoration:none;" class="e-header__link e-active e-fw-bld e-pd-20 e-d-flex e-align-center e-justify-between"
        data-dropdown-target="submenu">
        <span class="e-fs-14 e-d-flex e-align-center"><i
            class="ri-dashboard-line e-mg-r-10"></i>{{ user.company.name }}{{user.profile.name }} </span>
        <i class="ri-arrow-down-s-line"></i>
      </a>
      <ul class="e-dropdown__menu" id="submenu">

        <li><a href="index.html" class="e-header__sublink e-d-block e-pd-x-20 e-pd-y-10 e-active">Project</a>
        </li>
        <li><a href="ecommerce.html" class="e-header__sublink e-d-block e-pd-x-20 e-pd-y-10">eCommerce</a>
        </li>
      </ul>
    </li>

    
    <li class="e-header__list">
          {% include 'wrapper/wrap/sidebar.html' %}
       
    </li>
    {% modelview_list  user %}
    
    <li class="e-header__list e-header__list--employee-of-month">
      <div class="e-card">
        <img src="{% static 'assets/dashboard/images/employee-month.jpg' %}" alt="Employee of the month">
        <div class="employee-details e-pd-20 e-ta-center">
          <h4>Employee of the month</h4>
          <h2>Casey W.</h2>
          <span class="e-fs-12 e-tt-capitalize">Senior software engineer</span>
        </div>
      </div>
    </li>

    <li class="e-header__list e-pd-x-20">
      <a href="#" class="e-btn e-d-flex e-pd-y-20">
        <span class="e-fs-16 e-d-flex e-align-center"><i class="ri-logout-box-r-line e-mg-r-10"></i>Log
          out</span>
      </a>
    </li>

  </ul><!-- .e-header__navitems ends -->