core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("mainapps.accounts.urls",namespace='account')),
    path('stock/', include("mainapps.stock.urls",namespace='stock')),
    path('inventory/', include("mainapps.inventory.urls",namespace='inventory')),
    path('company/', include("mainapps.company.urls",namespace='company')),
    path('', include("mainapps.common.urls",namespace='common')),
    path('management/', include("mainapps.management.urls",namespace='management')),
    # path('permission/', include("mainapps.permit.urls",namespace='permission')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

mainapps/accounts/urls.py
from django.urls import path,include
from .views import *
app_name='accounts'
urlpatterns=[
    
    path('',register_owner,name = 'signup'),
    path('signout/',signout, name='logout'),
    path('signin/',login_owner, name='signin'),
    path('register/',RegisterPage.as_view(), name='register'),
    # path('signin/',signin, name='signin'),
    path('welcome/',LandingPage.as_view(), name='land'),
    path('verification/',twofa, name='verification'),
    path('send_code',send_code,name='send_code'),
]

mainapps/common/urls.py
from django.urls import path
from .views import *
app_name='common'
urlpatterns = [
    path('',HomEPage.as_view(),name='home'),
    path('add/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxTabGenericCreateView.as_view(), name='add_item'),
    
    
    ###################################################################################
    # ajax
    path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('add-address/', add_address, name='add_address'),
    path('get-regions/', get_regions, name='get_regions'),
    path('get-subregions/', get_subregions, name='get_subregions'),
    path('get-cities/', get_cities, name='get_cities'),
]

mainapps/permit/urls.py
from django.urls import path,include
from .views import *

urlpatterns=[
    path('',permit_home, name='permisions')
]

mainapps/accounts/api/views.py
from django.contrib.auth import login as api_login, logout as api_logout
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.conf import settings


from rest_framework import viewsets
from rest_framework.parsers import FormParser,MultiPartParser,JSONParser,FileUploadParser
from rest_framework.decorators import action,api_view
from rest_framework.request import Request
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework import generics,permissions

from rest_framework_simplejwt.views import TokenObtainPairView

from mainapps.accounts.models import User,VerificationCode,BlacklistedToken
from mainapps.accounts.views import send_html_email
from .serializers import *



class AuthApi(viewsets.ModelViewSet):
    queryset=User.objects.all()
    serializer_class=UserSerializer
    permission_classes=[permissions.IsAuthenticated,]
    # def get_queryset(self):

    #     return User.objects.filter(username=self.request.user.username).first()

class RegistrationAPI(APIView):
    
    def post(self,request):
        serializer=UserRegistrationSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        user=User.objects.get(username=request.data['username'])
        # request.session['pk']=user.pk
        # request.session["verified "]=False
        return Response({'message':f"User with the email {request.COOKIES.get('email')}  created"},status=201)
    # def get(self,request)

class UploadProfileView(APIView):
    parser_classes=[FileUploadParser]
    def post(self, request ):
        user=request.user
        print(user)
        picture=request.data["file"]
        print(request.data["file"])
        user.picture=picture
        user.save()
        #serializer=UserPictureSerializer(picture,data=request.data)
        if user.picture==picture:
            print("saved")
            return Response("Profile picture updated Successfully",status=200)
        else:
            return Response("Error uploading picture!",status=400)
class LoginAPIView(APIView):
    
    def post(self,request):
        serializer=LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user=serializer.validated_data["user"]
        # session_cookies=request.COOKIES.get('username')
        # request.session['pk']=user.pk
        # request.session["verified "]=False

        return Response("Verify Your Identity",status=200)


@api_view(['GET'])
def ge_route(request):
    route=['/api/token','api/token/refresh']
    return Response(route,status=201)
class VerificationAPI(APIView):
    def get(self,request):
        email=request.COOKIES.get('email')
        get_user=User.objects.get(username=email)
        verified=False
        pk=get_user.pk
        
        if verified:  
            return Response("Authentication Successful",status=200)
        else:
            if pk:
                # print(f'pk: {pk}')
                user =User.objects.get(pk=pk)
                html_file='verify.html'
                to_email=user.email
                from_email= settings.EMAIL_HOST_USER
                code=VerificationCode.objects.get(slug=user.email)
                code.total_attempts+=1
                code.save()
                code=VerificationCode.objects.get(slug=user.email)
                print(f'this is the code: {code}')
                subject=f'Verification code: {code}. {user.first_name} {user.last_name}'
                message= code
                send_html_email(subject, message, from_email, to_email,html_file)
                return Response("Confirmation code has been sent to your registered email",status=200)
    def post(self,request):
        email=request.COOKIES.get('email')
        get_user=User.objects.get(username=email)
        verified=request.COOKIES.get('verified')
        pk=get_user.pk
        user =User.objects.get(pk=pk)
        code=VerificationCode.objects.get(slug=user.email)
        # print(f'this is the code: {code}')
        serializer=VerificationSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        num=serializer.data['code']        
        if str(code)==str(num):
            # response= RefreshToken.for_user(user=user)
            api_login(request,user)
            response=Response()
            response.data={'message':'Authentication Successful'}
            response.status_code=200
            response.set_cookie(key='pk', value=str(user.pk))
            return response
        else :
            return Response("You have entered an invalid code and therefore need to restart Authentication for security reasons",status=400)
{
    "email":"ubongpr20@gmail.com",
    "username":"ubongpr20@gmail.com",
    "password":"prosuj@Pr20"
}             
        
class TokenGenerator(TokenObtainPairView):
    def post(self, request: Request, *args, **kwargs)  :
        username=request.data.get('username')
        password=request.data.get('password')
        user=authenticate(username=username,password=password)
        if user is not None:
            response=super().post(request,*args,**kwargs)
            response.status_code=200
            return response
        else:
            return Response(status=400)
class UserProfileView(APIView):
    
    permission_classes=[permissions.IsAuthenticated]
    def get(self,request):
        serializer=UserSerializer
        email=request.COOKIES.get('email')
        user=User.objects.get(username=email)
        return Response({'user':user},status=200)

class LogoutAPI(APIView):
    permission_classes=[permissions.IsAuthenticated,]
    def post(self,request):        
        response=Response()
        response.data={
            'message':'Logged Out Successfully'
        }
        response.status_code=200
        api_logout(request)
        return response
    

class ProfilePhotoModelSerialiserView(APIView):
    permission_classes=[permissions.IsAuthenticated]
    parser_classes=[FormParser,MultiPartParser]
    # queryset=ProfilePhoto.objects.all()
    # serializer_class=ProfilePhotoModelSerialiser

    # def create(self, request, *args, **kwargs):
    #     user=request.user
    #     picture=request.data['picture']
    #     ProfilePhoto.objects.create(picture=picture,user=user)
    #     print('done creating')
    #     return Response({'message':'Profile photo uploaded successfully'},status=200)
    def post(self,request,format=None):
        user=request.user
        print(user)
        serializer=ProfilePhotoModelSerialiser(data=request.data,context={'user':user})
        if serializer.is_valid():
            serializer.save()
            print(f'saved {serializer.data}')
            return Response(serializer.data,status=200)
        else:
            print(serializer.errors)
            return Response({'message':'Bad request'},status=500)

mainapps/accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate,logout
from django.views import generic
from django.contrib import messages
from django.conf import settings
from django.urls import reverse

from .forms import CustomUserCreationForm, CustomLoginForm
from django.contrib.auth import authenticate, login as auth_login


from mainapps.email_system.emails import send_html_email


from .models import User,VerificationCode
 







class LandingPage(generic.TemplateView):
    template_name='accounts/landing_page.html'

class LoginPage(generic.TemplateView):
    template_name='accounts/login.html'

class RegisterPage(generic.TemplateView):
    template_name='accounts/register.html'




def register_owner(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():

            user = form.save()
            user.is_main=True
            user.save()
            
            messages.success(request, 'Account created successfully. We have sent a verification code to your email. Use it to verify but do not expose it to anyone!')
            request.session['pk']=user.pk
            request.session["verified "]=False
            print(request.session['pk'])
            return redirect(reverse('account:verification')) 
            # return redirect(reverse('common:home'))
            # return redirect(reverse('accounts:send_code'))
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/create.html', {'form': form,'title':'Root User Registration'})

def login_owner(request):
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                # Explicitly specify the backend
                if user.is_main: 
                    auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    next_url= request.GET.get('next')
                    if next_url:
                        return redirect(next_url)
                    else:    
                        return redirect(reverse('common:home'))
                else:
                    form.add_error(None, "Wrong authentication method! Try Staff Login ")

                # return redirect(reverse('accounts:send_code'))
            else:
                # Invalid login
                form.add_error(None, "Invalid username or password")
    else:
        form = CustomLoginForm()
    return render(request, 'accounts/create.html', {'form': form,'title':"Root User Signin"})


def get_verification(request):
    pass 

def index(request):
  return render(request, 'index.html')
  
def signout(request):
    logout(request)
    messages.success(request,'Logout Successful')
    return redirect('/')
    
def signin(request):
    title='Signin'

    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            
            messages.success(request, 'We have sent a verification code to your email.')
            request.session['pk']=user.pk
            request.session["verified "]=False

            return redirect('/accounts/verification') 
        else:
            messages.error(request, 'Invalid username or password.')
            return render(request ,'accounts/login.html')
    return render(request, 'accounts/login.html',{'title':title})
        
def send_code(request):
    pk =request.session.get('pk')
    verified=request.session.get("verified ")

    if pk:
        user= User.objects.get(pk=pk)
        code =VerificationCode.objects.get(slug=user.username)
        code.total_attempts+=1
        code.save()
        code =VerificationCode.objects.get(slug=user.username)
        print(code)
        messages.success(request,'Code sent')
        return redirect('/verification')
    else:
        messages.error(request,'Session expired')
        return redirect('/signin')
    return redirect('/account/verification')



def twofa(request):
    title="Authentications"
    pk=request.session.get('pk')
    verified=request.session.get("verified ")

    if verified:  
        return redirect("/")
    else:
        if pk:
            print(f'pk: {pk}')
            user =User.objects.get(pk=pk)
            html_file='accounts/verify.html'
            to_email=user.email
            code=VerificationCode.objects.get(slug=user.email)
            code.total_attempts+=1
            code.save()
            code =VerificationCode.objects.get(slug=user.username)
            
            print(f'this is the code: {code}')
            subject=f'Verification code: {code}. {user.first_name} {user.last_name}'
            message= code
            
            
            if request.method!="POST":
            
                
                send_html_email(subject, message,  [to_email],html_file)
            if request.method=="POST":
                
                num=request.POST.get('code')
                print(num)
                
                if str(code)==num:
                    code.successful_attempts+=1
                    code.save()
                    login(request, user)
                    messages.success(request,"Authentication Successful!")
                    request.session["verified "]=True
                    
                    return redirect('/')
                else :
                    messages.error(request,"You have entered an invalid code and therefore need to restart Authentication for security reasons")
                    return redirect('/accounts/signin')
    return render(request,"accounts/twofa.html",{'title':title})
def get_verification(request):
    pass 

def register(request):
    title="Registration"
    if request.method == 'POST':
        username = request.POST.get('email1')
        email = request.POST.get('email2')
        first_name=request.POST.get('first_name') 
        last_name=request.POST.get('last_name') 
        password = request.POST.get('password1')
        confirm_password = request.POST.get('confirm_password')
        if not (username and email and password and confirm_password):
            messages.error(request, 'All fields are required.')
            return render(request, 'authentication-register.html')

        if password != confirm_password:
            messages.error(request, 'Passwords do not match.')
            return render(request, 'authentication-register.html')


        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already exists.')
            return render(request, 'authentication-register.html')

        user = User.objects.create_user(username=username,first_name=first_name,last_name=last_name, email=email, password=password)

        user = authenticate(username=username, password=password)
        
        messages.success(request, 'Account created successfully. We have sent a verification code to your email. Use it to verify but do not expose it to anyone!')
        request.session['pk']=user.pk
        request.session["verified "]=False

        return redirect('/account/verification')  

    return render(request, 'authentication-register.html',{'title':title})

mainapps/permit/views.py
from django.shortcuts import render,HttpResponse
from .permit import *
from django.conf import settings
User= settings.AUTH_USER_MODEL
# Create your views here.
def permit_home(request):
    permisions=get_all_permissions()
    user_permission=get_model_permission(User)
    
    context= {
        'all_permisions': permisions,
        'userpermisions': user_permission,
    }
    return render(request,'permit.html',context) 

templates/accounts/create.html
{% extends "wrapper/un_auth/base.html" %}
{%load bootstrap5 %}
{% load static %}
{% block page_title %}{{ title }}{% endblock page_title %}
    {% block more_meta_tags %}

    {% endblock %}
    
    {% block extra_style %}
    
    {% endblock extra_style %}

    {% block content %}
    
    <div class="container mx-auto p-4 w-3/4">
        <h1 class="text-3xl font-semibold text-blue-700 mb-8">{{ title }}</h1>
        <form action="." method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
              <button type="submit" class="btn btn-primary">
                Submit
              </button>
            {% endbuttons %}
          </form>
    </div>        
        {% endblock content %}

    {% block extra_script %}

    {% endblock extra_script %}

templates/accounts/landing_page.html
{% extends "wrapper/un_auth/base.html" %}

{% load static %}
{% load bootstrap5 %}

    {% block more_meta_tags %}

    {% endblock %}
    
    {% block extra_style %}
    
    {% endblock extra_style %}

    

        {% block content %}
            landing content here!
        {% endblock content %}

    {% block extra_script %}

    {% endblock extra_script %}

templates/accounts/login.html
{% extends "wrapper/un_auth/base.html" %}

{% load static %}
{% load bootstrap5 %}

    {% block more_meta_tags %}

    {% endblock %}
    
    {% block extra_style %}
    
    {% endblock extra_style %}

    

        {% block content %}
            Login content here!
        {% endblock content %}

    {% block extra_script %}

    {% endblock extra_script %}

templates/accounts/permit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    permission
</body>
</html>

templates/accounts/register.html
{% extends "wrapper/un_auth/base.html" %}

{% load static %}
{% load bootstrap5 %}

    {% block more_meta_tags %}

    {% endblock %}
    
    {% block extra_style %}
    
    {% endblock extra_style %}

    

        {% block content %}
            register content here!
        {% endblock content %}

    {% block extra_script %}

    {% endblock extra_script %}

templates/accounts/twofa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.16.0/font/bootstrap-icons.css" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'assets/css/auth.css' %}">
	<title>{{title}}</title>
	

	
</head>
<body>
  
	<div class="container">
	    
		<form id="loginForm" method="POST" action="{% url 'accounts:verification' %}" class="login active">
		  {% csrf_token %}
		 	        
	            
	           
			<h2 class="title">Enter verification code </h2>
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}

			<div class="form-group">
				
			<div class="form-group">
				<label for="password">Code</label>
				<div class="input-group">
					<input type="password" pattern=".{6}" id="password" name="code" placeholder="Verification code">
					<i class='bx bx-lock-alt' ></i>
				</div>
				<span class="help-text">A 6 digit code sent your email</span>
			</div>
	
				
			<button type="submit" class="btn-submit">Verify</button>
			</div>
			
			<p>
			    <span id="countdown">timer</span>
			 <a class="btn btn-secondary" id="resendLink" href="{% url 'accounts:verification' %}">Resend code</a>
                  
			
			</p>
			
		</form>
		
		
		
		   
  

<script>
document.addEventListener("DOMContentLoaded", function() {
  var link = document.getElementById("resendLink");
  var countdown = document.getElementById("countdown");
  
  var secondsLeft = 60;
  link.style.display= "none"
  plural='seconds'
  function updateCountdown() {
    countdown.innerText = "You can generate another code after "+ secondsLeft + " "+plural;
    secondsLeft--;
    if(secondsLeft==1){
        plural="second"
    }
    if (secondsLeft < 0) {
      clearInterval(interval);
      countdown.style.display = "none"; 
      link.style.display = "block"; 
    }
  }

  updateCountdown();
  var interval = setInterval(updateCountdown, 1000);
});
</script>



 


        
        
        

	
</body>
</html>

templates/accounts/verify.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            padding: 20px;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .container {
            max-width: 400px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            text-align: center;
        }
        .logo {
            width: 80px;
            margin: 0 auto 20px;
        }
        h1 {
            margin-bottom: 20px;
        }
        p {
            margin-bottom: 30px;
            color: #666;
        }
        .code {
            font-size: 24px;
            color: #333;
            margin-bottom: 10px;
        }
        .note {
            color: #999;
        }
        .footer {
            margin-top: 20px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- <img src="{% static 'images/logo.png' %}" alt="AFFM" class="logo"> -->
        <h1>{{ subject }}</h1>
        <p>Please use the following code to verify your email:</p>
        <div class="code">{{ message }}</div>
        <p class="note">This code will expire in 10 minutes and if you did not try to authenticate, you can ignore.</p>
        <div class="footer">
            This email was sent by pharm-inventory
        </div>
    </div>
</body>
</html>