core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("mainapps.accounts.urls",namespace='account')),
    path('stock/', include("mainapps.stock.urls",namespace='stock')),
    path('inventory/', include("mainapps.inventory.urls",namespace='inventory')),
    path('company/', include("mainapps.company.urls",namespace='company')),
    path('', include("mainapps.common.urls",namespace='common')),
    path('management/', include("mainapps.management.urls",namespace='management')),
    # path('permission/', include("mainapps.permit.urls",namespace='permission')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

mainapps/common/urls.py
from django.urls import path
from .views import *
app_name='common'
urlpatterns = [
    path('',HomEPage.as_view(),name='home'),
    path('add/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxTabGenericCreateView.as_view(), name='add_item'),
    
    
    ###################################################################################
    # ajax
    path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('add-address/', add_address, name='add_address'),
    path('get-regions/', get_regions, name='get_regions'),
    path('get-subregions/', get_subregions, name='get_subregions'),
    path('get-cities/', get_cities, name='get_cities'),
]

mainapps/company/urls.py
from django.urls import path
from .views import *

app_name='company'

urlpatterns = [
    path('create/<str:company_id>/<str:type>/', CompanyCreateView.as_view(), name='company_create'),
]

templates/wrapper/tags/model_list.html
{% if user.company  %}

    {% for app, models in apps_list %}
        <ul class="collapse nav flex-column ms-1" id="submenu1" data-bs-parent="#sidebar-wrapper">
            
            <li>
                <a href="#{{ app }}" class="nav-link e-fs-14 e-fw-bld link-light" data-bs-toggle="collapse">
                    {{ app }}
                </a>
                <ul class="collapse nav flex-column ms-1" id="{{ app }}" data-bs-parent="#submenu1">
                    {% for model in models %}
                        {% if  model == 'Company'%}
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.company.encrypted_id  'customer'  %}">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.company.encrypted_id  'manufacturer'  %}">Manufacture</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.company.encrypted_id  'supplier'  %}">Suppliers</a>
                            </li>
                        {% else %}

                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'common:add_item'  app.lower user.company.encrypted_id  model.lower|cut:' '  %}">{{model}}</a>
                            </li>
                        {%endif%}
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}    
{%elif user.profile %}

    {% for app, models in apps_list %}
        <ul class="collapse nav flex-column ms-1" id="submenu1" data-bs-parent="#sidebar-wrapper">
            
            <li>
                <a href="#{{ app }}" class="nav-link e-fs-14 e-fw-bld link-light" data-bs-toggle="collapse">
                    {{ app }}
                </a>
                <ul class="collapse nav flex-column ms-1" id="{{ app }}" data-bs-parent="#submenu1">
                    {% for model in models %}
                        {% if  model == 'Company'%}
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.profile.encrypted_id  'customer'  %}">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.profile.encrypted_id  'manufacturer'  %}">Manufacture</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'company:company_create' user.profile.encrypted_id  'supplier'  %}">Suppliers</a>
                            </li>
                        {% else %}

                            <li class="nav-item">
                                <a class="nav-link e-fs-14 e-fw-bld" href="{% url 'common:add_item'  app.lower user.profile.encrypted_id  model.lower|cut:' '  %}">{{model}}</a>
                            </li>
                        {%endif%}
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}    
{% endif %}    

templates/wrapper/tags/settings.html
{% if user.company  or user.profile %}
{% for app, models in settings_apps %}
<li class="dropdown-submenu">
    <a class="dropdown-item e-fs-14 e-fw-bld dropdown-toggle" href="#">{{ app }}</a>
    <ul class="dropdown-menu">
        {% for model in models %}
        <li><a class="dropdown-item e-fs-14 e-fw-bld" href="#">{{ model }}</a></li>
        {% endfor %}
    </ul>
</li>
{% endfor %}

{% endif  %}