core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("mainapps.accounts.urls",namespace='account')),
    path('stock/', include("mainapps.stock.urls",namespace='stock')),
    path('inventory/', include("mainapps.inventory.urls",namespace='inventory')),
    path('company/', include("mainapps.company.urls",namespace='company')),
    path('', include("mainapps.common.urls",namespace='common')),
    path('management/', include("mainapps.management.urls",namespace='management')),
    # path('permission/', include("mainapps.permit.urls",namespace='permission')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

mainapps/common/urls.py
from django.urls import path
from .views import *
app_name='common'
urlpatterns = [
    path('',HomEPage.as_view(),name='home'),
    path('add/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxTabGenericCreateView.as_view(), name='add_item'),
    
    
    ###################################################################################
    # ajax
    path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('list/<str:app_name>/<str:company_id>/<str:model_name>/', AjaxGenericList.as_view(), name='item_list'),
    # path('add-address/', add_address, name='add_address'),
    path('get-regions/', get_regions, name='get_regions'),
    path('get-subregions/', get_subregions, name='get_subregions'),
    path('get-cities/', get_cities, name='get_cities'),
]

mainapps/inventory/urls.py
from django.urls import path

from .views import *
app_name='inventory'
urlpatterns=[
    path('add-inventory-category/',add_category,name='add_inventory_category'),
    path('',InventoryHome.as_view(),name='inventory'),
    path('get-inventory-categories/',get_inventory_category,name='get_inventory_category'),
]

mainapps/common/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from cities_light.models import Country, Region, SubRegion,City

from mptt.models import MPTTModel, TreeForeignKey
from django.utils.crypto import get_random_string
from django.utils.text import slugify
from django.conf import settings
from mainapps.common.validators import validate_city, validate_city_belongs_to_sub_region, validate_country, validate_postal_code, validate_region, validate_region_belongs_to_country, validate_sub_region
from mainapps.content_type_linking_models.models import GenericModel
User= settings.AUTH_USER_MODEL


class ModelChoice(models.TextChoices):
    inventory='inventory','Inventory'
    stockitem='stock_item',"Stock item"
    company='company',"Company"
    policy='policy',"Policy"
    industry='industry',"Industry"

class TypeOf(MPTTModel):

    name = models.CharField(
        max_length=200, 
        # unique=True, 
        help_text='It must be unique', 
        verbose_name='Type'
    )
    which_model=models.CharField(max_length=30,choices=ModelChoice.choices,)
    slug = models.SlugField(max_length=230, editable=False,)
    is_active = models.BooleanField(default=True)
    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        related_name="children",
        null=True,
        blank=True
    )
    description=models.TextField(blank=True,null=True)

    class MPTTMeta:

        order_insertion_by = ["name"]

    class Meta:

        ordering = ["name"]

        verbose_name_plural = _("Types of Instances")
        constraints=[
            models.UniqueConstraint(
                fields=[
                    'name',
                    'which_model'
                ],
                name='unique_type_name_which_model'
            )
        ]




    def save(self, *args, **kwargs):

        self.slug = f"{get_random_string(6)}{slugify(self.name)}-{self.pk}-{get_random_string(5)}"

        super(TypeOf, self).save(*args, **kwargs)


    def __str__(self):

        return self.name



class Address(models.Model):

    class Meta:
        abstract= True

    
    country = models.ForeignKey(
        Country, 
        on_delete=models.CASCADE,
        verbose_name=_('Country'),
        null=True,
    )
    region = models.ForeignKey(
        Region, 
        on_delete=models.CASCADE,
        verbose_name=_('Region/State'),
        null=True,
    )
    subregion = models.ForeignKey(
        SubRegion, 
        on_delete=models.CASCADE,
        verbose_name=_('Sub region/LGA'),
        null=True,
    )
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        verbose_name=_('City/Town'),
        null=True,
     )
    apt_number = models.PositiveIntegerField(
        verbose_name=_('Apartment number'),
        null=True,
        blank=True
    )
    street_number = models.PositiveIntegerField(
        verbose_name=_('Street number'),
        null=True,
        blank=True
    )
    street = models.CharField(max_length=255,blank=False,null=True)

    postal_code = models.CharField(
        max_length=10,
        verbose_name=_('Postal code'),
        help_text=_('Postal code'),
        blank=True,
        null=True,
        validators=[validate_postal_code]
    )

    def __str__(self):
        return f'{self.street}, {self.city}, {self.region}, {self.country}'
    def clean(self):
        validate_country(self.country.id)
        validate_region(self.region.id)
        validate_sub_region(self.subregion.id)
        validate_city(self.city.id)
        validate_region_belongs_to_country(self.region.id, self.country.id)
        validate_city_belongs_to_sub_region(self.city.id, self.subregion.id)




class Attribute(models.Model):
    name = models.CharField(max_length=255)

class Value(models.Model):
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    value = models.CharField(max_length=255)
    class Meta:
        unique_together = ('attribute', 'value')
class Unit(models.Model):
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

class AttributeStore(GenericModel):
    attributes= models.JSONField(default=dict)


registerable_models=[Attribute,Value,Unit,AttributeStore,TypeOf]

mainapps/common/views.py
from django.db import transaction
from django.shortcuts import redirect, render
from django.views.generic import CreateView,TemplateView,ListView
from django.urls import reverse
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.apps import apps
from django.forms import modelform_factory
# Create your views here
from cities_light.models import Region, City,SubRegion

from mainapps.inventory.crud_logic import inventory_creation_logic
from mainapps.inventory.forms import InventoryCategoryForm
from mainapps.management.security.encripters import management_dispatch_dispatcher
from django.contrib.auth.mixins import LoginRequiredMixin





class HomEPage(TemplateView):
    # template_name='common/home.html'
    template_name='dashboard/index.html'


"""
#############Most reusable CreateView ever for non-inline_ models#######################################################################################

"""

class AjaxTabGenericCreateView(LoginRequiredMixin,CreateView):
    template_name = 'common/create.html'
    success_url='/'
    def get_model(self):
        model_name = self.kwargs['model_name']
        app_name = self.kwargs['app_name']
        return apps.get_model(app_name, model_name)

    def get_form_class(self):
        if self.kwargs['model_name'] == 'inventorycategory':
            return InventoryCategoryForm
        return modelform_factory(self.get_model(), fields='__all__')
        


    def dispatch(self, request, *args, **kwargs):
        management_dispatch_dispatcher(self=self,request=request)
        
        if not request.user.has_perm(f'{self.kwargs['app_name']}.add_{self.kwargs['model_name']}'): 
            print('no permission')  
            print(self.request.user) 
            # print(request.user.user_permissions.objects.all()) 
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        with transaction.atomic():
                
            if hasattr(self.get_model(),'profile'):
                if self.request.user.company:
                    form.instance.profile= self.request.user.company
                elif self.request.user.profile:
                    form.instance.profile= self.request.user.profile
            if hasattr(self.get_model(),'created_by'):
                form.instance.created_by = self.request.user
            # if self.kwargs['app_name'] == 'inventory':
            #     inventory_creation_logic(self,form)    
            response = super().form_valid(form)
            
            return response

    def form_invalid(self, form):
        
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs ) :
        context= super().get_context_data(**kwargs)
        context['form']=self.get_form()
    
    
        try:

            context['item_name'] = self.get_model()._meta.verbose_name.title()
        except Exception as error:
            context['item_name'] = self.get_model().__name__

            print(self.get_model().__name__ ,error)    

        try:

            context['plural'] = self.get_model()._meta.verbose_name_plural.title
        except Exception as error:
            print(self.get_model().__name__ ,error)    
        context['ajax_url'] = f'/add/{self.kwargs['app_name']}/{self.kwargs['model_name']}/' 
        context['get_url'] = f'/list/{self.kwargs['app_name']}/{self.kwargs['model_name']}/' 
        context['done_url'] = self.success_url
        return context







class AjaxGenericList(ListView):
    paginate_by = 3  
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 1)
        context['page_obj'] = context['paginator'].get_page(page)
    

        return context
    def dispatch(self, request, *args, **kwargs):
        management_dispatch_dispatcher(self=self,request=request)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        model = self.get_model()
        return model.objects.all()

    
    def get_model(self):
        model_name = self.kwargs['model_name']
        app_name = self.kwargs['app_name']
        return apps.get_model(app_name, model_name)
    
    def render_to_response(self, context, **response_kwargs):
        if self.request.method == 'GET':
            items = list(context['items'].values())
            return JsonResponse({
                'items': items,
                'pagination': {
                    'current_page': context['page_obj'].number,
                    'total_pages': context['paginator'].num_pages,
                    'has_previous': context['page_obj'].has_previous(),
                    'has_next': context['page_obj'].has_next(),
                }
            })
        return super().render_to_response(context, **response_kwargs)


"""
##############################################Location deals ######################################################
"""

def get_regions(request):
    country_id = request.GET.get('addresses-0-country')
    regions = Region.objects.filter(country_id=country_id)
    return render(request,'common/address/regions.html',{'regions':regions})

def get_subregions(request):
    region_id = request.GET.get('addresses-0-region')
    # subregions = SubRegion.objects.all()
    subregions = SubRegion.objects.filter(region_id=region_id)
    return render(request,'common/address/subregions.html',{'subregions':subregions})

def get_cities(request):
    subregion_id = request.GET.get('addresses-0-subregion')
    cities = City.objects.filter(subregion_id=subregion_id).values('id', 'name')
    return render(request,'common/address/cities.html',{'cities':cities})


"""
####################################################################################################
"""

templates/common/approve.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1>Unapproved Organizations</h1>
    <ul class="list-group">
        {% for organization in unapproved_organizations %}
            <li class="list-group-item">
                {{ organization.name }}
                <a href="{% url 'approve_organization' organization.pk %}" class="btn btn-success btn-sm float-right">Approve</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}




{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1>Approve Organization</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Approve</button>
    </form>
</div>
{% endblock %}

templates/common/create.html
{% extends "dashboard/wrapper/base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block more_meta_tags %}
{% endblock more_meta_tags %}

{% block page_title %}
    Inventory Creation
{% endblock page_title %}

{% block extra_style %}
{% endblock extra_style %}

{% block content %}
<div class="container mt-4" >



    <form method="post" class="form" id="create-form">
        {% csrf_token %}

        <div class="row mgb-20">
            <!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
            
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ plural }} </h5>                        
                        <div id="list-container" data-url="{{ get_url }}">
                
                            <!-- Companies will be loaded here via AJAX -->
                        </div>
                        <nav>
                            <ul class="pagination" id="pagination-container"></ul>
                        </nav>
                        <a href="#" class="btn btn-primary">View All</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->


        <div class="row">
        
                <br>
                <div class="col-lg-12 ">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Add new {{ item_name }}</h5>

                            {% for field in form %}
                            {% if field.name == "category"  %} 
                                
                                        {% bootstrap_field field %}
                                    
                                        <button type="button" hx-get="{% url 'inventory:add_inventory_category' %}" hx-target="#sub-form" hx-trigger="click" class="btn btn-outline-secondary " >
                                            Add new category
                                        </button>

                                <hr>
                            {% elif field.name == "company" %} 
                                
                                        {% bootstrap_field field %}
                                    
                                        <button type="button" class="btn btn-outline-secondary add-item-btn add-entry" data-field-name="{{ field.name }}" data-url="{% url 'common:add_item' app_name='inventory' model_name='inventorycategory' %}" onclick="openAddItemTab(this)">
                                            Add new company
                                        </button>

                                <hr>
                            {% else %}
                            {% bootstrap_field field %}
                            {% endif  %}

                        {% endfor %}
                        


                        </div>
                    </div>
                </div>
                <br>

                <div class="d-flex justify-content-between mt-3">
                    <button type="submit" class="btn btn-primary" name="action" value="add_another">Save</button>
                </div>
                
        </div>
    </form>
    
</div>
<div id="sub-form">

</div>
<!-- <div class="modal" tabindex="-1" id="sub-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="modal-body">

            </div>
        </div>
    </div>
</div> -->
{% endblock content %}

{% block extra_script %}
<script type="module" src="{% static 'assets/js/create_ajax.js' %}"></script>
<script>
    document.addEventListener("htmx:afterRequest",(event)=>{
        if (event.detail.target.id ==="model-body"){
            var modal =new bootstrap.Modal(document.getElementById('sub-form'));
            modal.show();
            console.log('shown')

        }
    })
    document.addEventListener('htmx:afterRequest',(e)=>{
        if (e.detail.verb ==="POST"){
            
            let newCategory=event.detail.xhr.response;
            let select=document.getElementById('id_category');
            let option=document.createElement('option');
            option.value=newCategory.id
            option.text=newCategory.name
            select.add(option);
            select.value=newCategory.id
            let modal =bootstrap.Modal.getInstance(document.getElementById('sub-form'))
            modal.hide();
        }
    })
</script>
{% endblock extra_script %}

templates/common/create_2.html
{% extends "wrapper/base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block more_meta_tags %}
{% endblock more_meta_tags %}

{% block page_title %}
    Inventory Creation
{% endblock page_title %}

{% block extra_style %}
{% endblock extra_style %}

{% block content %}
<div class="container mt-4">
    <h1>Create {{ type|title }} Company</h1>
    <div id="alert"></div>
    <form id="company-form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        <h3>Contacts</h3>
        {{ contacts.management_form }}
        <div id="contacts-formset">
            {% for form in contacts %}
                <div class="form-group">
                    {% bootstrap_form form %}
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-contact" class="btn btn-secondary">Add Contact</button>

        <h3>Addresses</h3>
        {{ addresses.management_form }}
        <div id="addresses-formset">
            {% for form in addresses %}
                <div class="form-group">
                    {% bootstrap_form form %}
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add-address" class="btn btn-secondary">Add Address</button>

        <button type="button" id="add-another" class="btn btn-primary">Add Another</button>
        <button type="button" id="submit-done" class="btn btn-success">Done</button>
    </form>

    <div id="companies-list">
        <!-- Companies will be loaded here via AJAX -->
    </div>
</div>
{% endblock content %}

{% block extra_script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    let contactFormCount = '{{ contacts.total_form_count }}';
    let addressFormCount = '{{ addresses.total_form_count }}';

    function updateFormNumbers(formTemplate, formCount, prefix) {
        formTemplate.find('input, select, textarea').each(function() {
            const name = $(this).attr('name').replace(/-\d+-/, `-${formCount}-`);
            $(this).attr('name', name);
            const id = $(this).attr('id').replace(/-\d+-/, `-${formCount}-`);
            $(this).attr('id', id);
        });
        formTemplate.find('label').each(function() {
            const newFor = $(this).attr('for').replace(/-\d+-/, `-${formCount}-`);
            $(this).attr('for', newFor);
        });
    }

    $('#add-contact').click(function() {
        const formTemplate = $('#contacts-formset .form-group:first').clone();
        updateFormNumbers(formTemplate, contactFormCount, 'contacts');
        $('#contacts-formset').append(formTemplate);
        contactFormCount++;
    });

    $('#add-address').click(function() {
        const formTemplate = $('#addresses-formset .form-group:first').clone();
        updateFormNumbers(formTemplate, addressFormCount, 'addresses');
        $('#addresses-formset').append(formTemplate);
        addressFormCount++;
    });

    function validateForm() {
        let isValid = true;
        $('#company-form .form-control').each(function() {
            if ($(this).prop('required') && $(this).val() === '') {
                isValid = false;
                $(this).addClass('is-invalid');
            } else {
                $(this).removeClass('is-invalid');
            }
        });
        return isValid;
    }

    function handleFormSubmit(event, url, clearForm) {
        event.preventDefault();
        if (!validateForm()) {
            $('#alert').html('<div class="alert alert-danger">Please fill in all required fields.</div>').show();
            return;
        }

        $.ajax({
            url: url,
            type: 'POST',
            data: $('#company-form').serialize(),
            dataType: 'json',
            success: function(response) {
                if (response.success) {
                    $('#alert').html('<div class="alert alert-success">Successfully submitted!</div>').show();
                    if (clearForm) {
                        $('#company-form')[0].reset();
                    } else {
                        window.location.href = response.redirect_url;
                    }
                } else {
                    $('#alert').html('<div class="alert alert-danger">' + response.errors + '</div>').show();
                }
            }
        });
    }

    $('#add-another').on('click', function(event) {
        handleFormSubmit(event, window.location.href, true);
    });

    $('#submit-done').on('click', function(event) {
        handleFormSubmit(event, window.location.href, false);
    });

    setTimeout(function() {
        $('#alert').fadeOut('slow');
    }, 10000);

    $('#alert').on('click', '.close', function() {
        $(this).parent().fadeOut('slow');
    });

    function fetchCompanies() {
        $.ajax({
            url: '{% url "fetch_companies" %}',
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                var companiesList = $('#companies-list');
                companiesList.empty();
                data.forEach(function(company) {
                    companiesList.append('<div><a href="/company/' + company.id + '/">' + company.name + '</a> - ' + company.address__street + '</div>');
                });
            }
        });
    }

    fetchCompanies();
});
</script>
{% endblock extra_script %}

templates/common/create_inline.html
{% extends "dashboard/wrapper/base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block more_meta_tags %}
{% endblock more_meta_tags %}

{% block page_title %}
    Add new {{ type }} 
{% endblock page_title %}

{% block extra_style %}
{% endblock extra_style %}

{% block content %}
<div class="container mt-4 cp-20">
    <form id="create-form8" action="." method="post">
        {% csrf_token %}
        <div class="row mgb-20">
<!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
    
                <div class="col-lg-12 e-mg-y-10">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Companies </h5>                        
                            <div id="list-container" data-url="{{ get_url }}">
                    
                                <!-- Companies will be loaded here via AJAX -->
                            </div>
                            <nav>
                                <ul class="pagination" id="pagination-container"></ul>
                            </nav>
                            <a href="#" class="btn btn-primary">View All</a>
                        </div>
                    </div>
                </div>
        </div>
                <br>
<!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->

                <div class="col-lg-12 e-mg-y-10 ">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Create {{ type }} </h5>
                            {% bootstrap_form form %}
                        </div>
                    </div>
                </div>
                <br>


                <!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->
         <div class="row mgb-20">

            <div class="col-lg-12 col-md-12 col-sm-12 e-mg-y-10">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ type }} Address</h5>
                        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                        {{ addresses.management_form }}
                        <div id="addresses-formset">
                                <div class="form-group">
                                    {% bootstrap_formset addresses layout='horizontal' %}
                                    <hr>
                                </div>

                            </div>
                            
                    </div>
                </div>
            </div>
            <br>
            
<!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->


            <div class="col-lg-12 col-md-12 col-sm-12 border-box e-mg-y-10">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"> Contact Person</h5>
                        {{ contacts.management_form }}
                        <div id="contacts-formset">
                                <div class="form-group">
                                    {% bootstrap_formset contacts layout='horizontal' %}
                                    <hr>
                                </div>

                
                        </div>
                
                    </div>
                </div>
                <br>
                
            </div>

            <br>

<!-- ########################################################################################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ -->

            
        </div>
        <div class="d-flex justify-content-between mt-3">

            <button type="submit" id="add-another1" class="btn btn-primary">Save </button>
        </div>

    </form>

</div>
<br>




{% endblock content %}

{% block extra_script %}
<script type="module" src="{% static 'assets/js/inline_create_ajax.js' %}"></script>

{% endblock extra_script %}

templates/common/home.html
{% extends "dashboard/wrapper/base.html" %}
{% load static %}

{% block more_meta_tags %}
    
{% endblock %}



{% block page_title %}
      
{% endblock page_title %}





{% block extra_style %}
   
{% endblock extra_style %}



{% block content %}
   
{% endblock content %}



{% block extra_script %}
    
{% endblock extra_script %}

templates/common/inpage_form.html
{% load bootstrap5 %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Add inventory category</h5>
        <form hx-post="{% url 'inventory:add_inventory_category' %}" hx-target="#modal-body" method="POST">
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">Add <button>
        </form>
    </div>
</div>